config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
    get'welcome/logged'
    get 'players/index'
    get 'characters/class'
    get 'characters/stats'

  
#TODO Nest resources according to Active Record Associations
  resources :dms
  resources :players
  resources :characters
  resources :npcs
  resources :games

root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/character.rb
class Character < ApplicationRecord
	belongs_to :player
	has_many :games
	has_many :dms, through: :games
end

app/models/dm.rb
class Dm < ApplicationRecord
	has_many :games, dependent: :destroy
	has_many :npcs, dependent: :destroy
	has_many :characters, through: :games
end

app/models/game.rb
class Game < ApplicationRecord
	belongs_to :dm 
	has_many :npcs, through: :dm
	has_many :characters
	has_many :players, through: :characters
end

app/models/npc.rb
class Npc < ApplicationRecord
	belongs_to :dm
	has_many :games, through: :dm
end

app/models/player.rb
class Player < ApplicationRecord
	has_many :characters
	has_many :games, through: :characters
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
	

	def index
	end

	def show
	end

	def new
		render 'new_character'
	end

	def edit
	end

	def create
	end

	def update
	end

	def destroy
	end

end

app/controllers/dms_controller.rb
class DmsController < ApplicationController
	
	def index
	end

	def show
	end

	def new
	end

	def edit
	end

	def create
	end

	def update
	end

	def destroy
	end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
	
	def index
	end

	def show
	end

	def new
		render 'new_game'
	end

	def edit
	end

	def create
	end

	def update
	end

	def destroy
	end

end

app/controllers/npcs_controller.rb
class NpcsController < ApplicationController

	def index
	end

	def show
	end

	def new
		render 'new_npc'
	end
	
	def edit
	end

	def create
	end

	def update
	end

	def destroy
	end

end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
	
	def index
	end

	def show
	end

	def new
	end

	def edit
	end

	def create
	end

	def update
	end

	def destroy
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/dms_helper.rb
module DmsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/npcs_helper.rb
module NpcsHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/characters/class.html.erb
<head>
<title>Dragon Master</title>
<!--- Text changing script --->
<meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no, shrink-to-fit=no">


</head> 
<script type="text/javascript" src="info.js"></script>

<body>
<div id="flip"><img src ="/assets/index/rotate.png", class ="rotate">

<p class="fliptext"> Flip Your Phone</p>
</div>
    

<div id="lab">Choose Your Class
</div>
<div id="info">
    <hr3><b id="boldStuff">Select your class.</Br> </br> Your class will affect your atributes through out the character creations process, so be sure to choose carefully. </br></br>Click on the different races to learn more about each!</b> </hr3>    
    
    </div>  

<div id="page">
<input type="image" src="/assets/race/player.png" class="socialicon" alt="Social Icon" onclick='halfling()' />
<input type="image"src="/assets/race/player.png" class="socialicon" alt="Social Icon" onclick='dwarf()' value='Change Text'/>
<input type="image" src="/assets/race/player.png" class="socialicon" alt="Social Icon"/>
    </br>
<input type="image"src="/assets/race/player.png" class="socialicon" alt="Social Icon"/>
<input type="image" src="/assets/race/player.png" class="socialicon" alt="Social Icon"/>
<input type="image" src="/assets/race/player.png" class="socialicon" alt="Social Icon"/>
</div>                  

<div id="button">
    
    <%= link_to characters_stats_path do %>
    <%= image_tag "/assets/race/next.png", class: "buttonicon"%>
<% end %>


</div>
<%= javascript_include_tag('race.js') %>
</body>

app/views/characters/index.html.erb
<h1>Character Index</h1>
<p>Find me at app/views/characters/index.html.erb!</p>


app/views/characters/new_character.html.erb
<head>
<title>Blagg Law ~ Chicago</title>
<!--- Text changing script --->
<meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no, shrink-to-fit=no">


</head> 

<body>
<div id="flip"><img src ="/assets/index/rotate.png", class ="rotate">

<p class="fliptext"> Flip Your Phone</p>
</div>
    

<div id="lab">Choose Your Race
</div>
<div id="info">
    <hr3><b id="boldStuff">Select your class.</Br> </br> Your class will affect your atributes through out the character creations process, so be sure to choose carefully. </br></br>Click on the different races to learn more about each!</b> </hr3>    
    
    </div>  

<div id="page">
<input type="image" src="/assets/race/halfling.jpg" class="socialicon" alt="Social Icon" onclick='halfling()'value='Change Text' />
<input type="image"src="/assets/race/dwarf.jpg" class="socialicon" alt="Social Icon" onclick='dwarf()' value='Change Text'/>
<input type="image" src="/assets/race/gnome.jpg" class="socialicon" alt="Social Icon" onclick='gnome()' value='Change Text'/>
    </br>
<input type="image"src="/assets/race/elf.jpg" class="socialicon" alt="Social Icon" onclick='elf()' value='Change Text'/>
<input type="image" src="/assets/race/human.jpg" class="socialicon" alt="Social Icon" onclick='human()' value='Change Text'/>
<input type="image" src="/assets/race/orc.jpg" class="socialicon" alt="Social Icon" onclick='orc()' value='Change Text'/>
</div>                  

<div id="button">
    
    <%= link_to characters_class_path do %>
    <%= image_tag "/assets/race/next.png", class: "buttonicon"%>
<% end %>


</div>
<%= javascript_include_tag('race.js') %>
</body>

app/views/characters/race/index.html.erb
<head>
<title>Blagg Law ~ Chicago</title>
<!--- Text changing script --->
<script type="text/javascript" src="info.js"></script>


</head>

<body bgcolor="#666666">
<div id="lab">
<h2> Choose Your Race </h2>
</div>
<div id="guide">
</div>
<div id="info">
    <h3><b id="boldStuff">Select your class.</Br> </br> Your class will affect your atributes through out the character creations process, so be sure to choose carefully. </br></br>Click on the different races to learn more about each!</b> </h3>    
    
    </div>    
<div id="page">
<input type="image" src="/assets/race/player.png" class="socialicon" alt="Social Icon" onclick='halfling()' />
<input type="image"src="/assets/race/player.png" class="socialicon" alt="Social Icon" onclick='dwarf()' value='Change Text'/>
<input type="image" src="/assets/race/player.png" class="socialicon" alt="Social Icon"/>
    </br>
<input type="image"src="/assets/race/player.png" class="socialicon" alt="Social Icon"/>
<input type="image" src="/assets/race/player.png" class="socialicon" alt="Social Icon"/>
<input type="image" src="/assets/race/player.png" class="socialicon" alt="Social Icon"/>
</div>                  

<div id="button">

<a href=class.html>
<img border="0" src="/assets/race/next.png" class ="tav", style="width:150px;height:75px;">
</a>

</div>
</body>

app/views/characters/stats.html.erb
<head>
<title>Dragon Master</title>
<!--- Text changing script --->
<meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no, shrink-to-fit=no">
</head> 

<body>

<div id="flip"><img src ="/assets/index/rotate.png", class ="rotate">

<p class="fliptext"> Flip Your Phone</p>
</div>
    
<div id="lab">
Base Stats
</div>
<div id="page1"> </div>

<div id="statlab">
<p>Strength:</p>  
<p>Constitution:</p> 
<p>Dexterty:</p>
<p>Intelligence:</p>  
<p>Chrismia:</p>
<p>Wisdom:</p>
</div>
    
<div id="statnlab">
<p><b id="strength"></p>  
<p><b id="constitution"></p> 
<p><b id="dext"></p>
<p><b id="intell"></p>  
<p><b id="chris"></p>
<p><b id="wisdom"> </p>
</div>
    
<div id="skilllab">
<p>Skill Points: <b id="points"></p>
    </div>

<div id='bmlab'>
<p>BM Str:</p>
<p>BM Con:</p>  
<p>BM Dex:</p>  
<p>BM Int:</p>  
<p>BM Chr:</p>  
<p>BM Wis:</p>
</div>
    
<div id='bmnlab'>
<p><b id="basestr"></p>
<p><b id="basecon"></p>  
<p><b id="basedex"></p>  
<p><b id="baseint"></p>  
<p><b id="basechr"></p>  
<p><b id="basewis"></p>
</div>


<div id='butlab'>
<input type="image" src="/assets/stat/up.png" class="valicon" onclick='str_1()' />
<input type="image" src="/assets/stat/down.png" class="valicon" onclick='str_0()' /></br>
<input type="image" src="/assets/stat/up.png" class="valicon" onclick='con_1()' />
<input type="image" src="/assets/stat/down.png" class="valicon" onclick='con_0()' /></br>
<input type="image" src="/assets/stat/up.png" class="valicon" onclick='dex_1()' />
<input type="image" src="/assets/stat/down.png" class="valicon" onclick='dex_0()' /></br>
<input type="image" src="/assets/stat/up.png" class="valicon" onclick='int_1()' />
<input type="image" src="/assets/stat/down.png" class="valicon" onclick='int_0()' /></br>
<input type="image" src="/assets/stat/up.png" class="valicon" onclick='chr_1()' />
<input type="image" src="/assets/stat/down.png" class="valicon" onclick='chr_0()' /></br>
<input type="image" src="/assets/stat/up.png" class="valicon" onclick='wis_1()' />
<input type="image" src="/assets/stat/down.png" class="valicon" onclick='wis_0()' /></br>
</div>

<div id="button1">
    
    <%= link_to characters_class_path do %>
    <%= image_tag "/assets/race/next.png", class: "buttonicon"%>
<% end %>


</div>


</body>
<%= javascript_include_tag('bstat.js') %>

app/views/dms/index.html.erb
<!-- Call Scripts for Functions -->
<link rel="stylesheet" href="https://code.jquery.com/ui/1.9.2/themes/base/jquery-ui.css" />
<script type="text/javascript" src="https://code.jquery.com/jquery.min.js"></script>
<script type="text/javascript" src="https://code.jquery.com/ui/1.9.2/jquery-ui.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui-touch-punch/0.2.3/jquery.ui.touch-punch.min.js"></script>

<meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no, shrink-to-fit=no">

<!-- Call Board Css -->

<!-- Call Javascript for Wedpage -->

<%= javascript_include_tag('html2canvas.js') %>
<%= javascript_include_tag('grid.js') %>

<!-- Visuals for Board -->
<body>
    
<div id="flip"><img src ="/assets/index/rotate.png", class ="rotate">

<p class="fliptext"> Flip Your Phone</p>
    
</div>    
    
<!-- Pallets for Tiles -->
<div id="brush2">
    <br>
    <div class="roof" ></div><br><br>
    <div class="roof1" ></div><br><br>
    <div class="wall" ></div><br><br>
    <div class="table" ></div><br><br>
    <div class="door" ></div><br><br>
    <div class="wind" ></div><br><br>
</div>    

<div id="brush1">
    <br>
    <div class="square" ></div><br><br>
    <div class="square2" ></div><br><br>
    <div class="water" ></div><br><br>
    <div class="tree" ></div><br><br>
    <div class="well" ></div><br><br>
</div>
    

<!-- Boarders for Buttons -->
<div id="plyscr"></div>

    
<!-- Buttons -->
<div id="showland"><input type="image" src="assets/board/land.png" class="landicon" onclick='showb1()'/>
</div>
<div id="showbuilding"><input type="image" src="assets/board/buld.png" class="buldicon" onclick='showb2()'/></div>
    
<div id="cam"><input type="image" src="assets/board/camera.png" class="camicon" id="Save"/>
    </div>
    
<div id="camt"><p style="color:white; font-size:3.2vh; font-weight:bold;"> Save Map</p></div>
<div id="emscr"></div>
<div id="trash"></div>
    
<!-- Game Board and Squares -->
<div id="gameboard">
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>

    
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>

    
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>

    
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>

    
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div> 

    <div class="squaredotted"></div>
    
     <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div> 
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div>
    <div class="squaredotted"></div> 
    <div class="squaredotted"></div>
    <div class="squaredotted"></div> 
    <div class="squaredotted"></div>

</div>
   


</body>

app/views/games/index.html.erb
<h1>Game Index</h1>
<p>Find me at app/views/games/index.html.erb!</p>

app/views/games/new_game.html.erb
<h1>New Game</h1>
<p>Find me at app/views/games/new_game.html.erb!</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DnD</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/npcs/index.html.erb
<h1>NPC Index</h1>
<p>Find me at app/views/npcs/index.html.erb!</p>

app/views/npcs/new_npc.html.erb
<h1>New NPC</h1>
<p>Find me at app/views/npcs/new_npc.html.erb!</p>

app/views/players/index.html.erb
<head>
<title>Dragon Master</title>
<meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no, shrink-to-fit=no">
</head>
<script type="text/javascript" src="http://code.jquery.com/jquery.min.js"></script>
<body bgcolor="#666666">
    
<div id="flip"><img src ="/assets/index/rotate.png", class ="rotate">

<p class="fliptext"> Flip Your Phone</p>
</div>
    
<div id="bar">
    
<%= link_to characters_path do %>
    <%= image_tag "players/dwarf.png", class: "dwarf"%>
<% end %>

<%= link_to games_path do %>
<%= image_tag "players/magic.png", class: "book"%>
<% end %>
    
<%= link_to new_character_path do %>
<%= image_tag "players/board.png", class: "board"%>
<% end %>
    
  
</div>             
<div id="fairy">
</div>

<div id="dis1">
<h7> Here you can create a new character!</h7>
</div>
    
<div id="dis2">
    <h7>Here you can view and edit your existing charaters!</h7>
</div>
    
<div id="dis3">
<h7> Here you can view your on going quests!</h7>
</div>   

<div id="conban">
</div>
<audio controls autoplay loop>

  <source src="0.ogg" type="audio/ogg">
  <source src="0.mp3" type="audio/mpeg">
Your browser does not support the audio element.
    </audio>
    

</body>

app/views/welcome/index.html.erb
<head>

<title>Dragon Master</title>
<meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no, shrink-to-fit=no">
</head>
<script type="text/javascript" src="https://code.jquery.com/jquery.min.js"></script>

<div id="flip"><img src ="/assets/index/rotate.png", class ="rotate">

<p class="fliptext"> Flip Your Phone</p>
</div>

<div id="map">
 
<%= image_tag "scroll.png", class: "log"%>

<%= image_tag "index/hos.png", class: "hos"%>

<%= image_tag "index/wiz.png", class: "wiz"%>

<%= image_tag "index/tav.png", class: "tav"%>
    
<%= image_tag "index/logo.png", class: "logo"%>

<img src ="/assets/index/bar.png", class ="bar">   
<img src ="/assets/index/kn.png", class ="kn">
<img src ="/assets/index/arch.png", class ="arc">   
<img src ="/assets/index/mon.png", class ="mon">   
</div> 


<div id="logtext">
<form action="/welcome/index" method="post">        
Username:<br>
<input type="text" name="Username" style="width: 22.5vw; font-size:100%; padding:0"><br><br>
Password:<br>
<input type="text" name="Password" style="width: 22.5vw; font-size:100%; padding:0"><br><br>
</form> 

<%= link_to welcome_logged_path do %>
    <%= image_tag "index/next.png", class: "button"%>
<% end %>   
</div>
    

</body>

app/views/welcome/logged.html.erb
<head>
<meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no, shrink-to-fit=no">

<title>Dragon Master</title>
</head>
<script type="text/javascript" src="https://code.jquery.com/jquery.min.js"></script>

<div id="flip"><img src ="/assets/index/rotate.png", class ="rotate">

<p class="fliptext"> Flip Your Phone</p>
    
</div>

<div id="map">
    
    <%= link_to players_path do %>
<%= image_tag "index/hos.png", class: "hos"%>
<% end %>    

<%= link_to dms_path do %>
<%= image_tag "index/wiz.png", class: "wiz"%>
<% end %>  

<%= link_to root_path do %>
<%= image_tag "index/tav.png", class: "tav"%>
<% end %>
    
<%= link_to root_path do %>
<%= image_tag "index/logo.png", class: "logo"%>
<% end %>

<%= link_to root_path do %>
<%= image_tag "index/drag.png", class: "dragon"%>
<% end %>
    
<!--<img src ="/assets/index/boat.png", class ="boat">-->
<img src ="/assets/index/bar.png", class ="bar">   
<img src ="/assets/index/kn.png", class ="kn">
<img src ="/assets/index/arch.png", class ="arc">   
<img src ="/assets/index/mon.png", class ="mon">   
</div> 
    

</body>